# De capítulos

In [1]:
# Celda 1: imports y configuración básica

import os
import pandas as pd

print("[DEBUG] Librerías cargadas correctamente")

[DEBUG] Librerías cargadas correctamente

In [2]:
# Celda 2: ruta y archivo a depurar

ruta_base = r"Valor_Presente_y_procesador/output"

# 👇 Cambia solo este nombre si tu CSV final se llama distinto
nombre_archivo_csv = "salida.csv"

ruta_csv = os.path.join(ruta_base, nombre_archivo_csv)
ruta_csv = r"C:\Users\aleja\Documents\Ingenieria Estadistica\Asignaturas2025B\arpro1\Base de Datos ARPRO\Valor_Presente_y_procesador\output\salida.csv"
df = pd.read_csv(ruta_csv)


print(f"[DEBUG] Ruta CSV: {ruta_csv}")

df = pd.read_csv(ruta_csv)
print(f"[DEBUG] DataFrame cargado con {len(df)} filas y {len(df.columns)} columnas")
df.head()

C:\Users\aleja\AppData\Local\Temp\ipykernel_12968\997651888.py:10: DtypeWarning: Columns (32,42,46) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(ruta_csv)

[DEBUG] Ruta CSV: C:\Users\aleja\Documents\Ingenieria Estadistica\Asignaturas2025B\arpro1\Base de Datos ARPRO\Valor_Presente_y_procesador\output\salida.csv

C:\Users\aleja\AppData\Local\Temp\ipykernel_12968\997651888.py:15: DtypeWarning: Columns (32,42,46) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(ruta_csv)

[DEBUG] DataFrame cargado con 143446 filas y 54 columnas

,Descripcion,Tipo,Codigo,UM,Presup_Cantidad,Presup_Valor,Proy_Cantidad,Proy_Valor,Dif_Cantidad,Dif_Valor,...,Codigo_Capitulo,Nombre_Capitulo,Codigo_Item,Nombre_Item,Nombre_Proyecto,Codigo_Proyecto,Estado_Proyecto,Fecha_De_Elaboracion,Fecha_De_Inicio,Fecha_De_Finalizacion
0,COSTOS DIRECTOS,NaN,NaN,NaN,NaN,1.499542e+10,NaN,1.957227e+10,NaN,-4.576849e+09,...,NaN,COSTOS DIRECTOS,NaN,NaN,Plaza de la Hoja,108,Finalizado,2013-12-17,2013-12-17,2015-12-17
1,1-PRELIMINARES,NaN,NaN,NaN,NaN,2.302874e+08,NaN,3.361586e+08,NaN,-1.058712e+08,...,1.0,PRELIMINARES,NaN,NaN,Plaza de la Hoja,108,Finalizado,2013-12-17,2013-12-17,2015-12-17
2,1.001-Localización y replanteo,NaN,NaN,NaN,6261.0,2.649569e+06,6261.0,2.551428e+06,0.0,9.814100e+04,...,1.0,PRELIMINARES,1.001,Localización y replanteo,Plaza de la Hoja,108,Finalizado,2013-12-17,2013-12-17,2015-12-17
3,comisión de topografía,O,1933.0,di,0.0,0.000000e+00,6.0,2.343000e+06,-6.0,-2.343000e+06,...,1.0,PRELIMINARES,1.001,Localización y replanteo,Plaza de la Hoja,108,Finalizado,2013-12-17,2013-12-17,2015-12-17
4,comisión de topografía replanteo,O,1934.0,m2,6261.0,2.126838e+06,0.0,-2.400000e+01,6261.0,2.126862e+06,...,1.0,PRELIMINARES,1.001,Localización y replanteo,Plaza de la Hoja,108,Finalizado,2013-12-17,2013-12-17,2015-12-17

In [3]:
# Celda 3: columnas y tipos

print("[DEBUG] Columnas disponibles:")
print(df.columns.tolist())

print("\n[DEBUG] Tipos de datos:")
print(df.dtypes)

[DEBUG] Columnas disponibles:
['Descripcion', 'Tipo', 'Codigo', 'UM', 'Presup_Cantidad', 'Presup_Valor', 'Proy_Cantidad', 'Proy_Valor', 'Dif_Cantidad', 'Dif_Valor', 'Contratado_Cantidad', 'Contratado_Valor', 'Comprado_Cantidad', 'Comprado_Valor', 'Asegurado_Cantidad', 'Asegurado_Valor', 'Invertido_Cantidad', 'Invertido_Valor', 'Consumido_Cantidad', 'Consumido_Valor', 'PorConsumir_Cantidad', 'PorConsumir_Valor', 'Desviacion_Valor', 'Norma1_ConsuMenorProy', 'Norma2_AsegMenorProy', 'Presup_Insumo', 'Presup_Item', 'Presup_Capitulo', 'Proy_Insumo', 'Proy_Item', 'Proy_Capitulo', 'Estado', 'Macroproyecto', 'IPC_Historico', 'Factor_IPC', 'Presup_Insumo_VP', 'Presup_Item_VP', 'Presup_Capitulo_VP', 'Proy_Insumo_VP', 'Proy_Item_VP', 'Proy_Capitulo_VP', 'Tipo_Fila', 'Codigo_Estructura', 'Nombre_Estructura', 'Codigo_Capitulo', 'Nombre_Capitulo', 'Codigo_Item', 'Nombre_Item', 'Nombre_Proyecto', 'Codigo_Proyecto', 'Estado_Proyecto', 'Fecha_De_Elaboracion', 'Fecha_De_Inicio', 'Fecha_De_Finalizacion']

[DEBUG] Tipos de datos:
Descripcion               object
Tipo                      object
Codigo                   float64
UM                        object
Presup_Cantidad          float64
Presup_Valor             float64
Proy_Cantidad            float64
Proy_Valor               float64
Dif_Cantidad             float64
Dif_Valor                float64
Contratado_Cantidad      float64
Contratado_Valor         float64
Comprado_Cantidad        float64
Comprado_Valor           float64
Asegurado_Cantidad       float64
Asegurado_Valor          float64
Invertido_Cantidad       float64
Invertido_Valor            int64
Consumido_Cantidad       float64
Consumido_Valor          float64
PorConsumir_Cantidad     float64
PorConsumir_Valor        float64
Desviacion_Valor         float64
Norma1_ConsuMenorProy     object
Norma2_AsegMenorProy      object
Presup_Insumo            float64
Presup_Item              float64
Presup_Capitulo          float64
Proy_Insumo              float64
Proy_Item                float64
Proy_Capitulo            float64
Estado                    object
Macroproyecto             object
IPC_Historico            float64
Factor_IPC               float64
Presup_Insumo_VP         float64
Presup_Item_VP           float64
Presup_Capitulo_VP       float64
Proy_Insumo_VP           float64
Proy_Item_VP             float64
Proy_Capitulo_VP         float64
Tipo_Fila                 object
Codigo_Estructura         object
Nombre_Estructura         object
Codigo_Capitulo          float64
Nombre_Capitulo           object
Codigo_Item               object
Nombre_Item               object
Nombre_Proyecto           object
Codigo_Proyecto            int64
Estado_Proyecto           object
Fecha_De_Elaboracion      object
Fecha_De_Inicio           object
Fecha_De_Finalizacion     object
dtype: object

In [4]:
# Celda 4: conteo por Tipo_Fila

if "Tipo_Fila" in df.columns:
    print("[DEBUG] Conteo por Tipo_Fila:")
    print(df["Tipo_Fila"].value_counts(dropna=False))
else:
    print("[DEBUG] La columna 'Tipo_Fila' no existe en el CSV")

[DEBUG] Conteo por Tipo_Fila:
Tipo_Fila
INSUMO      118319
ITEM         23859
CAPITULO      1165
TOTAL          103
Name: count, dtype: int64

In [ ]:
# Celda 5: muestra de cada tipo

columnas_a_ver = [
    col for col in [
        "Descripcion",
        "Tipo_Fila",
        "Codigo_Capitulo",
        "Nombre_Estructura",
        "Nombre_Capitulo",
        "Nombre_Item",
        "capitulo_homologado",
        "Nombre_Proyecto",
    ] if col in df.columns
]

print("[DEBUG] Columnas usadas para la inspección:")
print(columnas_a_ver)

for tipo in ["CAPITULO", "ITEM", "INSUMO", "TOTAL"]:
    print("\n" + "=" * 60)
    print(f"[DEBUG] Ejemplos de Tipo_Fila = {tipo}")
    print("=" * 60)
    if "Tipo_Fila" in df.columns:
        display(df[df["Tipo_Fila"] == tipo][columnas_a_ver].head(10))
    else:
        print("No hay columna 'Tipo_Fila' en este DataFrame.")

[DEBUG] Columnas usadas para la inspección:
['Descripcion', 'Tipo_Fila', 'Codigo_Estructura', 'Nombre_Estructura', 'Nombre_Capitulo', 'Nombre_Item', 'Nombre_Proyecto']

============================================================
[DEBUG] Ejemplos de Tipo_Fila = CAPITULO
============================================================

,Descripcion,Tipo_Fila,Codigo_Estructura,Nombre_Estructura,Nombre_Capitulo,Nombre_Item,Nombre_Proyecto
0,COSTOS DIRECTOS,CAPITULO,NaN,COSTOS DIRECTOS,COSTOS DIRECTOS,NaN,Plaza de la Hoja
1,1-PRELIMINARES,CAPITULO,1.0,PRELIMINARES,PRELIMINARES,NaN,Plaza de la Hoja
278,2-CIMENTACION,CAPITULO,2.0,CIMENTACION,CIMENTACION,Cambio cable red M.T.,Plaza de la Hoja
515,4-ESTRUCTURA,CAPITULO,4.0,ESTRUCTURA,ESTRUCTURA,Protección talud excavación Tanques de agua,Plaza de la Hoja
867,5-MAMPOSTERIA,CAPITULO,5.0,MAMPOSTERIA,MAMPOSTERIA,Malla electrosoldada estructura,Plaza de la Hoja
942,6-PAÑETES,CAPITULO,6.0,PAÑETES,PAÑETES,Nicho regulador gas,Plaza de la Hoja
955,7-CUBIERTAS Y CIELORASOS,CAPITULO,7.0,CUBIERTAS Y CIELORASOS,CUBIERTAS Y CIELORASOS,Pañete muros impermeabilizados tanque.,Plaza de la Hoja
985,8-IMPERMEABILIZACIONES,CAPITULO,8.0,IMPERMEABILIZACIONES,IMPERMEABILIZACIONES,Cubierta y muro verde,Plaza de la Hoja
1000,9-PISOS,CAPITULO,9.0,PISOS,PISOS,Impermeabilización cubierta,Plaza de la Hoja
1081,10-ENCHAPES,CAPITULO,10.0,ENCHAPES,ENCHAPES,Afinado de piso shut basura,Plaza de la Hoja

============================================================
[DEBUG] Ejemplos de Tipo_Fila = ITEM
============================================================

,Descripcion,Tipo_Fila,Codigo_Estructura,Nombre_Estructura,Nombre_Capitulo,Nombre_Item,Nombre_Proyecto
2,1.001-Localización y replanteo,ITEM,1.001,Localización y replanteo,PRELIMINARES,Localización y replanteo,Plaza de la Hoja
9,1.005-Cerramiento en lona altura=2.00m,ITEM,1.005,Cerramiento en lona altura=2.00m,PRELIMINARES,Cerramiento en lona altura=2.00m,Plaza de la Hoja
20,1.006-Puerta acceso obra,ITEM,1.006,Puerta acceso obra,PRELIMINARES,Puerta acceso obra,Plaza de la Hoja
26,1.010-Campamento,ITEM,1.01,Campamento,PRELIMINARES,Campamento,Plaza de la Hoja
75,1.011-Poceta cilindros,ITEM,1.011,Poceta cilindros,PRELIMINARES,Poceta cilindros,Plaza de la Hoja
83,1.012-Lavallantas,ITEM,1.012,Lavallantas,PRELIMINARES,Lavallantas,Plaza de la Hoja
94,1.013-Desarenador,ITEM,1.013,Desarenador,PRELIMINARES,Desarenador,Plaza de la Hoja
102,1.014-Burro para hierro,ITEM,1.014,Burro para hierro,PRELIMINARES,Burro para hierro,Plaza de la Hoja
105,1.015-Caseta para vigilante,ITEM,1.015,Caseta para vigilante,PRELIMINARES,Caseta para vigilante,Plaza de la Hoja
107,1.020-Vía provisional y patios,ITEM,1.02,Vía provisional y patios,PRELIMINARES,Vía provisional y patios,Plaza de la Hoja

============================================================
[DEBUG] Ejemplos de Tipo_Fila = INSUMO
============================================================

,Descripcion,Tipo_Fila,Codigo_Estructura,Nombre_Estructura,Nombre_Capitulo,Nombre_Item,Nombre_Proyecto
3,comisión de topografía,INSUMO,NaN,comisión de topografía,PRELIMINARES,Localización y replanteo,Plaza de la Hoja
4,comisión de topografía replanteo,INSUMO,NaN,comisión de topografía replanteo,PRELIMINARES,Localización y replanteo,Plaza de la Hoja
5,durmiente 3m ordinario,INSUMO,NaN,durmiente 3m ordinario,PRELIMINARES,Localización y replanteo,Plaza de la Hoja
6,mineral rojo,INSUMO,NaN,mineral rojo,PRELIMINARES,Localización y replanteo,Plaza de la Hoja
7,"puntilla con cabeza de 1""",INSUMO,NaN,"puntilla con cabeza de 1""",PRELIMINARES,Localización y replanteo,Plaza de la Hoja
8,"puntilla con cabeza de 2""",INSUMO,NaN,"puntilla con cabeza de 2""",PRELIMINARES,Localización y replanteo,Plaza de la Hoja
10,mano de obra preliminares ug,INSUMO,NaN,mano de obra preliminares ug,PRELIMINARES,Cerramiento en lona altura=2.00m,Plaza de la Hoja
11,concreto 1500 psi grava común,INSUMO,NaN,concreto 1500 psi grava común,PRELIMINARES,Cerramiento en lona altura=2.00m,Plaza de la Hoja
12,listón 0.02x0.01x3m,INSUMO,NaN,listón 0.02x0.01x3m,PRELIMINARES,Cerramiento en lona altura=2.00m,Plaza de la Hoja
13,"puntilla con cabeza de 1-1/2"" a 4"" (p)",INSUMO,NaN,"puntilla con cabeza de 1-1/2"" a 4"" (p)",PRELIMINARES,Cerramiento en lona altura=2.00m,Plaza de la Hoja

============================================================
[DEBUG] Ejemplos de Tipo_Fila = TOTAL
============================================================

,Descripcion,Tipo_Fila,Codigo_Estructura,Nombre_Estructura,Nombre_Capitulo,Nombre_Item,Nombre_Proyecto
2731,Totales,TOTAL,NaN,Totales,INDIRECTOS,Medidores de energía trifásico,Plaza de la Hoja
2734,TOTAL,TOTAL,NaN,TOTAL,INDIRECTOS,Medidores de energía trifásico,Plaza de la Hoja
5425,Totales,TOTAL,NaN,Totales,IMPREVISTOS,Descuentos a contratistas,Edificio 9111
5427,TOTAL,TOTAL,NaN,TOTAL,IMPREVISTOS,Descuentos a contratistas,Edificio 9111
8688,Totales,TOTAL,NaN,Totales,INDIRECTOS,Plan de manejo de tráfico (refrendación),BS Rosales
8691,TOTAL,TOTAL,NaN,TOTAL,INDIRECTOS,Plan de manejo de tráfico (refrendación),BS Rosales
10589,Totales,TOTAL,NaN,Totales,INDIRECTOS,Medidores de energía trifásico,Plaza de la Hoja (Etapa II)
10591,TOTAL,TOTAL,NaN,TOTAL,INDIRECTOS,Medidores de energía trifásico,Plaza de la Hoja (Etapa II)
14296,Totales,TOTAL,NaN,Totales,INDIRECTOS,Plan de manejo de tráfico (refrendación),Edificio Vive92.co
14299,TOTAL,TOTAL,NaN,TOTAL,INDIRECTOS,Plan de manejo de tráfico (refrendación),Edificio Vive92.co

### extra

In [9]:
# Celda 6: inspección de la jerarquía para un proyecto específico

# Puedes cambiar este valor:
nombre_proyecto_debug = None  # ej: "PROYECTO X"

filtro = pd.Series([True] * len(df))

if nombre_proyecto_debug and "Nombre_Proyecto" in df.columns:
    filtro = (df["Nombre_Proyecto"] == nombre_proyecto_debug)

df_debug = df[filtro]

print(f"[DEBUG] Filas para el filtro seleccionado: {len(df_debug)}")

columnas_jerarquia = [
    col for col in [
        "Descripcion",
        "Tipo_Fila",
        "Codigo_Estructura",
        "Nombre_Estructura",
        "Nombre_Capitulo",
        "Nombre_Item",
        "Nombre_Proyecto",
    ] if col in df_debug.columns
]

display(df_debug[columnas_jerarquia].head(30))

[DEBUG] Filas para el filtro seleccionado: 143446

,Descripcion,Tipo_Fila,Codigo_Estructura,Nombre_Estructura,Nombre_Capitulo,Nombre_Item,Nombre_Proyecto
0,COSTOS DIRECTOS,CAPITULO,NaN,COSTOS DIRECTOS,COSTOS DIRECTOS,NaN,Plaza de la Hoja
1,1-PRELIMINARES,CAPITULO,1.0,PRELIMINARES,PRELIMINARES,NaN,Plaza de la Hoja
2,1.001-Localización y replanteo,ITEM,1.001,Localización y replanteo,PRELIMINARES,Localización y replanteo,Plaza de la Hoja
3,comisión de topografía,INSUMO,NaN,comisión de topografía,PRELIMINARES,Localización y replanteo,Plaza de la Hoja
4,comisión de topografía replanteo,INSUMO,NaN,comisión de topografía replanteo,PRELIMINARES,Localización y replanteo,Plaza de la Hoja
5,durmiente 3m ordinario,INSUMO,NaN,durmiente 3m ordinario,PRELIMINARES,Localización y replanteo,Plaza de la Hoja
6,mineral rojo,INSUMO,NaN,mineral rojo,PRELIMINARES,Localización y replanteo,Plaza de la Hoja
7,"puntilla con cabeza de 1""",INSUMO,NaN,"puntilla con cabeza de 1""",PRELIMINARES,Localización y replanteo,Plaza de la Hoja
8,"puntilla con cabeza de 2""",INSUMO,NaN,"puntilla con cabeza de 2""",PRELIMINARES,Localización y replanteo,Plaza de la Hoja
9,1.005-Cerramiento en lona altura=2.00m,ITEM,1.005,Cerramiento en lona altura=2.00m,PRELIMINARES,Cerramiento en lona altura=2.00m,Plaza de la Hoja
10,mano de obra preliminares ug,INSUMO,NaN,mano de obra preliminares ug,PRELIMINARES,Cerramiento en lona altura=2.00m,Plaza de la Hoja
11,concreto 1500 psi grava común,INSUMO,NaN,concreto 1500 psi grava común,PRELIMINARES,Cerramiento en lona altura=2.00m,Plaza de la Hoja
12,listón 0.02x0.01x3m,INSUMO,NaN,listón 0.02x0.01x3m,PRELIMINARES,Cerramiento en lona altura=2.00m,Plaza de la Hoja
13,"puntilla con cabeza de 1-1/2"" a 4"" (p)",INSUMO,NaN,"puntilla con cabeza de 1-1/2"" a 4"" (p)",PRELIMINARES,Cerramiento en lona altura=2.00m,Plaza de la Hoja
14,"puntilla con cabeza de 2-1/2""",INSUMO,NaN,"puntilla con cabeza de 2-1/2""",PRELIMINARES,Cerramiento en lona altura=2.00m,Plaza de la Hoja
15,"puntilla con cabeza de 2""",INSUMO,NaN,"puntilla con cabeza de 2""",PRELIMINARES,Cerramiento en lona altura=2.00m,Plaza de la Hoja
16,"puntilla con cabeza de 3""",INSUMO,NaN,"puntilla con cabeza de 3""",PRELIMINARES,Cerramiento en lona altura=2.00m,Plaza de la Hoja
17,tela protección blanca x 2.10m,INSUMO,NaN,tela protección blanca x 2.10m,PRELIMINARES,Cerramiento en lona altura=2.00m,Plaza de la Hoja
18,tela protección verde x 2.10m,INSUMO,NaN,tela protección verde x 2.10m,PRELIMINARES,Cerramiento en lona altura=2.00m,Plaza de la Hoja
19,vara corredor 3m,INSUMO,NaN,vara corredor 3m,PRELIMINARES,Cerramiento en lona altura=2.00m,Plaza de la Hoja
20,1.006-Puerta acceso obra,ITEM,1.006,Puerta acceso obra,PRELIMINARES,Puerta acceso obra,Plaza de la Hoja
21,mano de obra preliminares ug,INSUMO,NaN,mano de obra preliminares ug,PRELIMINARES,Puerta acceso obra,Plaza de la Hoja
22,"acero figurado 1/4"" a 1"" 60000 psi (p)",INSUMO,NaN,"acero figurado 1/4"" a 1"" 60000 psi (p)",PRELIMINARES,Puerta acceso obra,Plaza de la Hoja
23,concreto 2500 psi grava común,INSUMO,NaN,concreto 2500 psi grava común,PRELIMINARES,Puerta acceso obra,Plaza de la Hoja
24,alambre negro no. 18,INSUMO,NaN,alambre negro no. 18,PRELIMINARES,Puerta acceso obra,Plaza de la Hoja
25,puerta acceso vehicular obra,INSUMO,NaN,puerta acceso vehicular obra,PRELIMINARES,Puerta acceso obra,Plaza de la Hoja
26,1.010-Campamento,ITEM,1.01,Campamento,PRELIMINARES,Campamento,Plaza de la Hoja
27,mano de obra preliminares ug,INSUMO,NaN,mano de obra preliminares ug,PRELIMINARES,Campamento,Plaza de la Hoja
28,bisagra 2 1/2,INSUMO,NaN,bisagra 2 1/2,PRELIMINARES,Campamento,Plaza de la Hoja
29,cadena eslabonada 3/8,INSUMO,NaN,cadena eslabonada 3/8,PRELIMINARES,Campamento,Plaza de la Hoja

# Celda 7: comparación Nombre_Capitulo vs capitulo_homologado

In [8]:
import os
import pandas as pd
import re


ruta_base = r"C:\Users\aleja\Documents\Ingenieria Estadistica\Asignaturas2025B\arpro1\Base de Datos ARPRO\Valor_Presente_y_procesador\output"

path_consolidado = os.path.join(ruta_base, "tablaLooker_sin_capitulos_homologados.csv")              # tu csv final
path_candidatos  = os.path.join(ruta_base, "homologacion_capitulos.csv")    # diccionario


# === 1. Cargar data ===
print("[DEBUG] Cargando consolidado y candidatos...")
data_frame_consolidado = pd.read_csv(path_consolidado)
data_frame_candidatos = pd.read_csv(path_candidatos)

# Nos quedamos solo con capítulos
data_frame_capitulos = data_frame_consolidado[
    data_frame_consolidado["Tipo_Fila"] == "CAPITULO"
].copy()

print(f"[DEBUG] Filas de capítulos en consolidado: {len(data_frame_capitulos)}")


# === 2. Deduplicar listas antes del merge ===
data_frame_capitulos_unicos = (
    data_frame_capitulos[["Codigo_Capitulo", "Nombre_Capitulo"]]
    .drop_duplicates()
    .copy()
)

print(f"[DEBUG] Capítulos únicos (Codigo_Capitulo, Nombre_Capitulo): {len(data_frame_capitulos_unicos)}")

data_frame_candidatos_unicos = (
    data_frame_candidatos[["query", "codigo_candidato", "descripcion_candidato"]]
    .drop_duplicates()
    .copy()
)

print(f"[DEBUG] Candidatos únicos (query, codigo_candidato, descripcion_candidato): {len(data_frame_candidatos_unicos)}")


# === 3. Normalizar y construir llaves de merge ===

def normalizar_capitulo(codigo, nombre):
    nombre_limpio = str(nombre).strip().upper()

    # Si el código es NaN, la llave es solo el nombre
    if pd.isna(codigo):
        return nombre_limpio

    codigo_limpio = str(codigo).strip()
    if "." in codigo_limpio:
        codigo_limpio = codigo_limpio.split(".", 1)[0]

    return f"{codigo_limpio} - {nombre_limpio}"



def normalizar_query(query: str) -> str:
    """
    Ejemplo: "10.0 - ENCHAPES" -> "10 - ENCHAPES"
    """
    if query is None:
        return ""

    texto = str(query).strip()
    partes = texto.split("-", 1)
    if len(partes) == 2:
        codigo_parte = partes[0].strip()
        nombre_parte = partes[1].strip().upper()
        # Nos quedamos solo con la parte antes del primer punto (10.0 -> 10)
        codigo_parte = codigo_parte.split(".", 1)[0].strip()
        return f"{codigo_parte} - {nombre_parte}"
    else:
        return texto.upper()


# Llave en consolidado: Codigo_Capitulo + Nombre_Capitulo
data_frame_capitulos_unicos["llave_capitulo"] = data_frame_capitulos_unicos.apply(
    lambda fila: normalizar_capitulo(fila["Codigo_Capitulo"], fila["Nombre_Capitulo"]),
    axis=1,
)

# Llave en diccionario: query normalizada
data_frame_candidatos_unicos["llave_query"] = data_frame_candidatos_unicos["query"].apply(
    normalizar_query
)

print("[DEBUG] Ejemplos de llaves normalizadas (capítulos):")
print(data_frame_capitulos_unicos[["Codigo_Capitulo", "Nombre_Capitulo", "llave_capitulo"]].head())

print("[DEBUG] Ejemplos de llaves normalizadas (candidatos):")
print(data_frame_candidatos_unicos[["query", "llave_query"]].head())


# === 4. Merge solo sobre listas sin duplicados ===

data_frame_merged = data_frame_capitulos_unicos.merge(
    data_frame_candidatos_unicos[["llave_query", "codigo_candidato", "descripcion_candidato"]],
    left_on="llave_capitulo",
    right_on="llave_query",
    how="left",
)

# Construimos columna homologada solo para debug
data_frame_merged["capitulo_homologado"] = data_frame_merged.apply(
    lambda fila: (
        f"{fila['codigo_candidato']} - {fila['descripcion_candidato']}"
        if pd.notna(fila["codigo_candidato"])
        else None
    ),
    axis=1,
)


# === 5. Estadística de cobertura (debug) ===

total_capitulos_unicos = len(data_frame_capitulos_unicos)
capitulos_homologados = data_frame_merged["capitulo_homologado"].notna().sum()
capitulos_no_homologados = total_capitulos_unicos - capitulos_homologados

print("\n===== ESTADÍSTICAS DE HOMOLOGACIÓN (CAPÍTULOS ÚNICOS) =====")
print(f"Total capítulos únicos en consolidado:     {total_capitulos_unicos}")
print(f"Capítulos con homologación encontrada:     {capitulos_homologados}")
print(f"Capítulos SIN homologación (faltantes):    {capitulos_no_homologados}")

if capitulos_no_homologados > 0:
    print("\n[DEBUG] Capítulos SIN homologación (muestra):")
    print(
        data_frame_merged[
            data_frame_merged["capitulo_homologado"].isna()
        ][["Codigo_Capitulo", "Nombre_Capitulo", "llave_capitulo"]]
        .head(20)
    )

print("\n[DEBUG] Ejemplos de capítulos homologados:")
print(
    data_frame_merged[
        data_frame_merged["capitulo_homologado"].notna()
    ][["Codigo_Capitulo", "Nombre_Capitulo", "capitulo_homologado"]]
    .head(20)
)


# === 6. Capítulos sin homologar (detalles) ===

capitulos_sin_homologar = data_frame_merged[
    data_frame_merged["capitulo_homologado"].isna()
].copy()

print(f"[DEBUG] Capítulos sin homologar: {len(capitulos_sin_homologar)}")

print("\n[DEBUG] Muestra de llaves de capítulos sin homologar:")
print(
    capitulos_sin_homologar[
        ["Codigo_Capitulo", "Nombre_Capitulo", "llave_capitulo"]
    ].head(20)
)

print("\n[DEBUG] Muestra de llaves disponibles en homologacion_capitulos:")
print(
    data_frame_candidatos_unicos[["query", "llave_query"]]
    .drop_duplicates()
    .head(20)
)

[DEBUG] Cargando consolidado y candidatos...

C:\Users\aleja\AppData\Local\Temp\ipykernel_12968\2193670827.py:14: DtypeWarning: Columns (20,32,49,53) have mixed types. Specify dtype option on import or set low_memory=False.
  data_frame_consolidado = pd.read_csv(path_consolidado)

[DEBUG] Filas de capítulos en consolidado: 1165
[DEBUG] Capítulos únicos (Codigo_Capitulo, Nombre_Capitulo): 113
[DEBUG] Candidatos únicos (query, codigo_candidato, descripcion_candidato): 119
[DEBUG] Ejemplos de llaves normalizadas (capítulos):
     Codigo_Capitulo  Nombre_Capitulo    llave_capitulo
0                NaN  COSTOS DIRECTOS   COSTOS DIRECTOS
1                1.0     PRELIMINARES  1 - PRELIMINARES
278              2.0      CIMENTACION   2 - CIMENTACION
515              4.0       ESTRUCTURA    4 - ESTRUCTURA
867              5.0      MAMPOSTERIA   5 - MAMPOSTERIA
[DEBUG] Ejemplos de llaves normalizadas (candidatos):
                query       llave_query
0     COSTOS DIRECTOS   COSTOS DIRECTOS
1  1.0 - PRELIMINARES  1 - PRELIMINARES
2   2.0 - CIMENTACION   2 - CIMENTACION
3    4.0 - ESTRUCTURA    4 - ESTRUCTURA
4   5.0 - MAMPOSTERIA   5 - MAMPOSTERIA

===== ESTADÍSTICAS DE HOMOLOGACIÓN (CAPÍTULOS ÚNICOS) =====
Total capítulos únicos en consolidado:     113
Capítulos con homologación encontrada:     113
Capítulos SIN homologación (faltantes):    0

[DEBUG] Ejemplos de capítulos homologados:
    Codigo_Capitulo                             Nombre_Capitulo  \
0               NaN                             COSTOS DIRECTOS
1               1.0                                PRELIMINARES
2               2.0                                 CIMENTACION
3               4.0                                  ESTRUCTURA
4               5.0                                 MAMPOSTERIA
5               6.0                                     PAÑETES
6               7.0                      CUBIERTAS Y CIELORASOS
7               8.0                        IMPERMEABILIZACIONES
8               9.0                                       PISOS
9              10.0                                    ENCHAPES
10             11.0  INSTALACIONES ELECTRICAS Y DE COMUNICACION
11             12.0               INSTALACIONES HIDROSANITARIAS
12             13.0                        INSTALACIONES DE GAS
13             15.0                          CARPINTERIA MADERA
14             16.0                        CARPINTERIA METALICA
15             17.0             APARATOS SANITARIOS Y DE COCINA
16             18.0                          EQUIPOS ESPECIALES
17             19.0                                     PINTURA
18             20.0          CERRADURAS, ESPEJOS Y NOMENCLATURA
19             23.0                              REMATES Y ASEO

                                  capitulo_homologado
0                                CD - COSTOS DIRECTOS
1                                    1 - PRELIMINARES
2                                     2 - CIMENTACION
3                                      4 - ESTRUCTURA
4                                     5 - MAMPOSTERIA
5                                         6 - PAÑETES
6                           7 - CUBIERTA Y CIELORASOS
7   8.01 - IMPERMEABILIZACIONES. Impermeabilizaciones
8                                           9 - PISOS
9                                       10 - ENCHAPES
10  11.02 - INSTALACIONES ELECTRICAS. Instalacione...
11                 12 - INSTALACIONES HIDROSANITARIAS
12                          13 - INSTALACIONES DE GAS
13                            15 - CARPINTERIA MADERA
14                          16 - CARPINTERIA METALICA
15  17.01 - APARATOS SANITARIOS Y DE COCINA. Apara...
16            18 - EQUIPOS E INSTALACIONES ESPECIALES
17                                       19 - PINTURA
18            20 - CERRADURAS, ESPEJOS Y NOMENCLATURA
19                                23 - REMATES Y ASEO
[DEBUG] Capítulos sin homologar: 0

[DEBUG] Muestra de llaves de capítulos sin homologar:
Empty DataFrame
Columns: [Codigo_Capitulo, Nombre_Capitulo, llave_capitulo]
Index: []

[DEBUG] Muestra de llaves disponibles en homologacion_capitulos:
                                                query  \
0                                     COSTOS DIRECTOS
1                                  1.0 - PRELIMINARES
2                                   2.0 - CIMENTACION
3                                    4.0 - ESTRUCTURA
4                                   5.0 - MAMPOSTERIA
5                                       6.0 - PAÑETES
6                        7.0 - CUBIERTAS Y CIELORASOS
7                          8.0 - IMPERMEABILIZACIONES
8                                         9.0 - PISOS
9                                     10.0 - ENCHAPES
10  11.0 - INSTALACIONES ELECTRICAS Y DE COMUNICACION
11               12.0 - INSTALACIONES HIDROSANITARIAS
12                        13.0 - INSTALACIONES DE GAS
13                          15.0 - CARPINTERIA MADERA
14                        16.0 - CARPINTERIA METALICA
15             17.0 - APARATOS SANITARIOS Y DE COCINA
16                          18.0 - EQUIPOS ESPECIALES
17                                     19.0 - PINTURA
18          20.0 - CERRADURAS, ESPEJOS Y NOMENCLATURA
19                              23.0 - REMATES Y ASEO

                                        llave_query
0                                   COSTOS DIRECTOS
1                                  1 - PRELIMINARES
2                                   2 - CIMENTACION
3                                    4 - ESTRUCTURA
4                                   5 - MAMPOSTERIA
5                                       6 - PAÑETES
6                        7 - CUBIERTAS Y CIELORASOS
7                          8 - IMPERMEABILIZACIONES
8                                         9 - PISOS
9                                     10 - ENCHAPES
10  11 - INSTALACIONES ELECTRICAS Y DE COMUNICACION
11               12 - INSTALACIONES HIDROSANITARIAS
12                        13 - INSTALACIONES DE GAS
13                          15 - CARPINTERIA MADERA
14                        16 - CARPINTERIA METALICA
15             17 - APARATOS SANITARIOS Y DE COCINA
16                          18 - EQUIPOS ESPECIALES
17                                     19 - PINTURA
18          20 - CERRADURAS, ESPEJOS Y NOMENCLATURA
19                              23 - REMATES Y ASEO

In [9]:
# === HOMOLOGACIÓN FINAL SOBRE TODO EL CONSOLIDADO ===

# 1. Crear la llave en TODO el consolidado
data_frame_consolidado["llave_capitulo"] = data_frame_consolidado.apply(
    lambda fila: normalizar_capitulo(
        fila["Codigo_Capitulo"],
        fila["Nombre_Capitulo"]
    ),
    axis=1,
)

# 2. Merge contra la tabla ya creada data_frame_merged (la tabla de mapeo)
data_frame_consolidado_homologado = data_frame_consolidado.merge(
    data_frame_merged[["llave_capitulo", "codigo_candidato", "descripcion_candidato"]],
    on="llave_capitulo",
    how="left",
)

# 3. Renombrar columnas finales
data_frame_consolidado_homologado = data_frame_consolidado_homologado.rename(
    columns={
        "codigo_candidato": "Codigo_Capitulo_Homologado",
        "descripcion_candidato": "Nombre_Capitulo_Homologado",
    }
)

# 4. Construir columna combinada de capítulo homologado
data_frame_consolidado_homologado["Capitulo_Homologado"] = data_frame_consolidado_homologado.apply(
    lambda fila: (
        f"{fila['Codigo_Capitulo_Homologado']} - {fila['Nombre_Capitulo_Homologado']}"
        if pd.notna(fila["Codigo_Capitulo_Homologado"])
        else None
    ),
    axis=1
)

print("[DEBUG] Listo: columnas nuevas agregadas al consolidado:")
print(
    data_frame_consolidado_homologado[
        ["Codigo_Capitulo_Homologado", "Nombre_Capitulo_Homologado", "Capitulo_Homologado"]
    ].head()
)

# 5. Guardar
path_consolidado_homologado = os.path.join(
    ruta_base, "salida_con_capitulos_homologados.csv"
)
data_frame_consolidado_homologado.to_csv(path_consolidado_homologado, index=False)
print(f"[DEBUG] Archivo guardado: {path_consolidado_homologado}")

[DEBUG] Listo: columnas nuevas agregadas al consolidado:
  Codigo_Capitulo_Homologado Nombre_Capitulo_Homologado   Capitulo_Homologado
0                         CD            COSTOS DIRECTOS  CD - COSTOS DIRECTOS
1                          1               PRELIMINARES      1 - PRELIMINARES
2                          1               PRELIMINARES      1 - PRELIMINARES
3                          1               PRELIMINARES      1 - PRELIMINARES
4                          1               PRELIMINARES      1 - PRELIMINARES
[DEBUG] Archivo guardado: C:\Users\aleja\Documents\Ingenieria Estadistica\Asignaturas2025B\arpro1\Base de Datos ARPRO\Valor_Presente_y_procesador\output\salida_con_capitulos_homologados.csv

# De items